include:
  - "cicd-config/.rules-ci.yml"
  - "cicd-config/.variables-ci.yml"

stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "pri-ui"
  CONTAINER_NAME: "pri-ui"
  DIST_PATH: dist

#unit-test:
##  extends:
##    - .common-rule
##  stage: test
##  script:
##    - echo "Running unit tests..."

before_script:
  - apt-get install -y nginx

cache:
  paths:
    - node_modules/

clean:
  extends:
    - .after-merge-rule
  stage: build
  script:
    - sudo docker stop $CONTAINER_NAME || true
    - sudo docker rm $CONTAINER_NAME || true
    - sudo docker rmi $IMAGE_NAME || true

build:
  extends:
    - .after-merge-rule
  stage: build
  script:
    - npm install
    - ng build --prod
    - sudo docker build --rm -t $IMAGE_NAME .

deploy:
  extends:
    - .after-merge-rule
  stage: deploy
  only:
    - main
  script:
    - sudo docker run -v /etc/letsencrypt/ssl:/etc/letsencrypt/ssl -d --name $CONTAINER_NAME --network=pri-network -p 443:443 $IMAGE_NAME
