include:
  - "cicd-config/.rules-ci.yml"
  - "cicd-config/.variables-ci.yml"

stages:
  - build
  - test
  - deploy

unit-test:
  tags:
    - test
  extends:
    - .common-rule
  stage: test
  script:
    - echo "Running unit tests..."
    # - cd /${CI_PROJECT_DIR}
    # - sudo npm install
    # - sudo npm run test

deploy_test_env:
  tags:
    - test
  extends:
    - .after-merge-rule
  stage: deploy
  before_script:
    - sudo docker version
  script:
    - echo "Deployment to test env..."
    - sudo docker stop pri-ui || true && sudo docker rm pri-ui || true 
    - sudo docker rmi pri-ui || true
    - sudo docker build --rm -t pri-ui .
    - sudo docker run -d --name pri-ui --network=pri-network -p 80:80 pri-ui

deploy_prod_env:
  tags:
    - prod
  extends:
    - .after-merge-rule-prod
  stage: deploy
  before_script:
    - sudo docker version
  script:
    - echo "Deployment to prod env..."
    # - sudo docker stop pri-ui || true && sudo docker rm pri-ui || true 
    # - sudo docker rmi pri-ui || true
    # - sudo docker build --rm -t pri-ui .
    # - sudo docker run -v /etc/letsencrypt/ssl:/etc/letsencrypt/ssl -d --name pri-ui --network=pri-network -p 443:443 pri-ui
