include:
  - "cicd-config/.rules-ci.yml"
  - "cicd-config/.variables-ci.yml"

stages:
  - build
  - test
  - deploy

clean:
  extends:
    - .common-rule
  stage: build
  script:
    - sudo docker stop pri-ui || true && sudo docker rm pri-ui || true 
    - sudo docker rmi pri-ui || true

build:
  extends:
    - .common-rule
  stage: build
  script:
    - sudo docker build --rm -t pri-ui .

code-analysis:
  extends:
    - .after-merge-rule
  stage: test
  script:
    - echo "Running SonarQube..."
    - echo "To be done..."

unit-test:
  extends:
    - .after-merge-rule
  stage: test
  script:
    - echo "Running unit tests..."

deploy:
  extends:
    - .common-rule
  stage: deploy
  before_script:
    - sudo docker version
  script:
    - sudo docker run -d --name pri-ui -p 4200:4200  pri-ui
