include:
  - "cicd-config/.rules-ci.yml"
  - "cicd-config/.variables-ci.yml"

stages:
  - build
  - test
  - deploy

clean:
  extends:
    - .common-rule
  stage: build
  script:
    - sudo docker stop pri-ui || true && sudo docker rm pri-ui || true 
    - sudo docker rmi pri-ui || true

build:
  extends:
    - .common-rule
  stage: build
  script:
    - sudo docker build -t pri-ui .

code-analysis:
  extends:
    - .common-rule
  stage: test
  script:
    - echo "Running SonarQube..."
    - echo "To be done..."

unit-test:
  extends:
    - .common-rule
  stage: test
  cache:
    key: "maven-$CI_COMMIT_REF_SLUG"
    paths:
      - .m2/repository
  script:
    - run unit tests

deploy:
  extends:
    - .common-rule
  stage: deploy
  before_script:
    - sudo docker version
  script:
    - sudo docker run -d --name pri-ui -p 4200:4200 pri-ui
