.common-rule:
  rules:
    - if: ($CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_BRANCH == 'main')

.after-merge-rule-prod:
  rules:
    - if: $CI_COMMIT_BRANCH == 'SYSPRI-356-Test-env-setup'
      when: manual

.after-merge-rule:
  rules:
    - if: $CI_COMMIT_BRANCH == 'SYSPRI-356-Test-env-setup'
