name: Docker Image CI

on:
  push:
    branches: [ "SYSPRI-999-Open-source-dev" ]
  pull_request:
    branches: [ "SYSPRI-999-Open-source-dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image with dev Nginx config (no ssl)
      run: docker build . --file Dockerfile --build-arg NGINX_PATH=nginx-dev.conf --tag pri-ui-no-ssl:$(date +%s)
    - name: Build the Docker image with prod Nginx config (ssl)
      run: docker build . --file Dockerfile --build-arg NGINX_PATH=nginx-prod.conf --tag pri-ui-ssl:$(date +%s)
