name: Docker Image CI

on:
  push:
    branches: [ "SYSPRI-999-Open-source-dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build and publish the Docker image without SSL config'
        run: |
          docker build . --build-arg NGINX_CONF=nginx-no-ssl.conf --tag pri-ui-no-ssl:$(date +%s)
          docker push ghcr.io/System-PRI/pri-ui-no-ssl:$(date +%s)

      - name: 'Build and publish the Docker image with SSL config'
        run: |
          docker build . --build-arg NGINX_CONF=nginx-ssl.conf --tag pri-ui-ssl:$(date +%s)
          docker push ghcr.io/System-PRI/pri-ui-ssl:$(date +%s)
